{% set version = "2.2.1" %}
{% set gh_org = "Anaconda-Platform" %}
{% set gh_repo = "nb_conda" %}
{% set build_num = 7 %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: ea202c17c85b0a1059698ba0b1005c5382ad1340bb6b6ffa464ed0e3781a923b

build:
  number: {{ build_num }}
  string: unix_{{ build_num }}  # [unix]
  string: win_{{ build_num }}   # [win]
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - jupyter nbextension install nb_conda --py --sys-prefix --overwrite

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
    - notebook >=4.3.1,<7.0.0

  run:
    - python >=3.7
    - notebook >=4.3.1,<7.0.0
    - nb_conda_kernels >=2.0.0
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - nb_conda

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda environment and package access extension from within Jupyter

extra:
  recipe-maintainers:
    - bollwyvl
    - damianavila
    - fjcapdevila
    - xylar
