travis:
  secure:
    BINSTAR_TOKEN: VSYffcjXN28duGzW22B9JmXNKH6hWXHV6nAiBdgl14/W79mUP37BAeDPdIHX0MLV7S35UJrAAgQc2qJfIRcoQjL+59pOGPEQWWgWoUw7rFLgXJaanmm8AOwOtabhS2ClLaDJBkjjNIyAKrKQGOCMRyUKLmjo2Vb0nn4tC+IiOJoXl64kTZhP5U24GQkitJkBIrZwYQreu1HLA39PlZWNM9wKYJAmnqSmOlh6TYVPucmzNm4aD/l4z4G+WNeKjnAvmnA9y8hu/xUS3yrVzhn2PLKacM8LcBfIDfe7PmHGoyjw2gnL/IePMsjVHlYiFGuztVpHDYDNLKiQQsne+ZBW65LSevMKijpHuuFLhuQWunO0Ow/7f4O5mBu0kvtVWjJ/jU6xwOp2XJ8LhB+BKxcJ47kUryw4zU5jTiEn7UycSTD9x8DNvAdV268sLqzJdNgsgpfqyHJzF7pZUXdkacHTtkEgo5/RgILIRhH0PlEy6MGuionsWPLhpwXRTU+Qofgdn7DGFNkvpAZ+F44StGaQYJfkB0UXLnkowFrUS+llJzIxpE13T92Ofl0ZWSc4sWZ01R7dN2uSqqsTbybdL4dV+nvWKPbETilxQAU4kjI1Ixfmcsbw/TVgmSmHRqdNkAZk9CmqU8MKSucLtlLRacvGTCmv32uR4vfJG4XQeDdW19k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
